### ISSUE TITLE
Do not block menu-items that contain submenus

### ISSUE THREAD

**Issue by TimvanSteenbergen** [bsgriggs/mendix-unsaved-changes-message#3] opened 2024-06-10 15:05 UTC
Great tool. Just one improvement that would make it even better:
When clicking on a menu-item, you would expect that click to just open up the menu, showint the sub-items, and without popping you the block question.

Best regards and have a nice day!

**Comment by bsgriggs** [comment] 2024-11-29 15:41
Duplicate of https://github.com/bsgriggs/mendix-unsaved-changes-message/issues/2

**Closed as completed by bsgriggs** 2024-11-29 15:41 UTC
Labels: duplicate
